version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: complaints_db
      MYSQL_USER: mindsdb_user
      MYSQL_PASSWORD: mindsdb_password
    ports:
      - "3306:3306"
    networks:
      - mindsdb_desktop_network  # Connects to the MindsDB extension network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mindsdb_desktop_network

networks:
  mindsdb_desktop_network:  
    external:
      name: mindsdb_mindsdb-docker-extension-desktop-extension_default

